// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace ParcialWebApi.Models;

public partial class Categoria
{
    [JsonIgnore]
    public int Id { get; set; }

    public string Nombre { get; set; }

    [JsonIgnore]
    public virtual ICollection<Criptomoneda> Criptomoneda { get; set; } = new List<Criptomoneda>();
}